### ISSUE TITLE
Permission to create volume and write to it

### ISSUE THREAD

**Issue by FrantisekSidak** [infologistix/docker-wsl2#1]
I have installed docker by your script on Ubuntu 20.04 in WSL2. For some reason I am not able to mount volume using docker-compose using snippet below. I have installed docker-compose binaries manually. Volume directory is not created (using relative path) or is not writable (using absolute path). Any idea where could be the problem could be?

I have tried to set metadata option in automount in /etc/wsl.conf.

Same works with docker desktop:
```
version: '3.4'

services:
  servicename:
    ...
    volumes:
      - ./data/storage:/data # relative path or
      - /mnt/c/.../data/storage:/data # absolute path
```
